@startuml

!theme sketchy


top to bottom direction
skinparam scale 1 width
skinparam scale 2 height
'skinparam dpi 5000

'skinparam nodesep 100
skinparam ranksep 150

!include .\\BlockCode.puml
!include .\\BlockDrag.puml
!include .\\BlockRotate.puml
!include .\\Extensions.puml
!include .\\PassDrag.puml
!include .\\SceneManagement.puml
!include .\\VRDebug.puml
!include .\\Interaction\ConnectionGrab.puml
!include .\\Interaction\DisplayButton.puml
!include .\\Interaction\fvInputManager.puml
!include .\\Interaction\fvInputModeManager.puml
!include .\\Interaction\HandRemover.puml
!include .\\Interaction\HandSpawner.puml
!include .\\Interaction\InitLogic.puml
!include .\\Interaction\ModeSetup.puml
!include .\\Interaction\MoveFly.puml
!include .\\Interaction\MoveGrab.puml
!include .\\Interaction\PanelButton.puml
!include .\\Interaction\SelectObject.puml
!include .\\Interaction\TransformGrab.puml
!include .\\LayerBottom\GameModeManager.puml
!include .\\LayerBottom\VRAction.puml
!include .\\LayerBottom\VRConnection.puml
!include .\\LayerBottom\VRData.puml
!include .\\LayerBottom\VREvent.puml
!include .\\LayerBottom\VRLogicElement.puml
!include .\\LayerBottom\VRManager.puml
!include .\\LayerBottom\VRObject.puml
!include .\\LayerBottom\VRPort.puml
!include .\\LayerBottom\VRProperty.puml
!include .\\LayerBottom\VRTab.puml
!include .\\LayerBottom\VRVariable.puml
!include .\\LayerSave\SaveElement.puml
!include .\\LayerSave\SaveManager.puml
!include .\\LayerTop\ActionPopulation.puml
!include .\\LayerTop\EventPopulation.puml
!include .\\LayerTop\GhostObject.puml
!include .\\LayerTop\MiniatureMaker.puml
!include .\\LayerTop\VisAction.puml
!include .\\LayerTop\VisConnection.puml
!include .\\LayerTop\VisEvent.puml
!include .\\LayerTop\VisLogicElement.puml
!include .\\LayerTop\VisManager.puml
!include .\\LayerTop\VisObject.puml
!include .\\LayerTop\VisPort.puml
!include .\\LayerTop\VisProperty.puml
!include .\\LayerTop\VisRecording.puml
!include .\\LayerTop\VisTab.puml
!include .\\LayerTop\VisVariable.puml
!include .\\TestScripts\ContentPopulation.puml
!include .\\TestScripts\TestLoad.puml
!include .\\UI\BetterColorPicker.puml
!include .\\UI\BetterToggle.puml
!include .\\UI\BezierCurve.puml
!include .\\UI\DropdownWorkaround.puml
!include .\\UI\DropShadow.puml
!include .\\UI\LoadingCircle.puml
!include .\\UI\Panel.puml
!include .\\UI\PanelHolder.puml
!include .\\UI\Tooltip.puml
!include .\\UI\TooltipContent.puml
!include .\\UI\TweenScaler.puml
!include .\\UI\UIBillboard.puml
!include .\\UI\UICenter.puml
!include .\\UI\UIHover.puml
!include .\\UI\VRCanvasScaler.puml
!include .\\UI\HoverFeedback\OnHoverLine.puml
!include .\\UI\HoverFeedback\OnHoverMove.puml
!include .\\UI\HoverFeedback\OnHoverScale.puml
!include .\\UI\HoverFeedback\OnHoverShake.puml
!include .\\UI\HoverFeedback\OnHoverTilt.puml
!include .\\UI\HoverFeedback\UIOnHoverEvent.puml
@enduml
